<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3html5videoplayer"
 *
 * Auto generated by Extension Builder 2016-03-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 't3html5videoplayer',
	'description' => 'Small lightweight Html5 Videoplayer for TYPO3 with additional Videoportal support of Youtube and Vimeo >= 6.2',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);